(defun setup-environment ()
  (setenv "PSARCHBIT" "64")
  (setenv "DIR_EXTLIB" "C:\\pslibs\\extlib")
  (setenv "CYGWIN" "nontsec nodosfilewarning")
  (setenv "VSINSTALLDIR" "C:\\pslibs\\extlib\\vstudio14")
  (setenv "VCINSTALLDIR" "C:\\pslibs\\extlib\\vstudio14\\VC")
  (setenv "VS140COMNTOOLS" "C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\")
  (setenv "VSSDK140Install" "C:\\pslibs\\extlib\\vstudio14\\VSSDK\\")
  (setenv "UCRTVersion" "10.0.10586.0")
  (setenv "UniversalCRTSdkDir" "c:\\pslibs\\extlib\\winsdk\\v10")
  (setenv "NETFXSDKDir" "C:\\pslibs\\extlib\\dotnet\\NETFXSDK\\4.6.1")
  (setenv "INCLUDE" "C:\\pslibs\\extlib\\vstudio14\\VC\\INCLUDE;C:\\pslibs\\extlib\\vstudio14\\VC\\ATLMFC\\INCLUDE;C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\include\\10.0.10586.0\\ucrt;C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\include\\10.0.10586.0\\shared;C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\include\\10.0.10586.0\\um;C:\\pslibs\\extlib\\winsdk\\v8.1\\Include\\um;C:\\pslibs\\extlib\\winsdk\\v8.1\\Include\\shared;C:\\pslibs\\extlib\\winsdk\\v8.1\\Include\\winrt;C:\\pslibs\\extlib\\winsdk\\v10\\Include\\10.0.10586.0\\ucrt")
  (setenv "LIB" "C:\\pslibs\\extlib\\vstudio14\\VC\\LIB\\amd64;C:\\pslibs\\extlib\\vstudio14\\VC\\ATLMFC\\LIB\\amd64;C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\lib\\10.0.10586.0\\ucrt\\x64;C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\lib\\10.0.10586.0\\um\\x64;C:\\pslibs\\extlib\\winsdk\\v8.1\\lib\\winv6.3\\um\\x64;C:\\pslibs\\extlib\\dotnet\\NETFXSDK\\4.6.1\\Lib\\um\\x64")
  (setenv "PATH" "C:\\pslibs\\extlib\\vstudio14\\Common7\\Tools\\Bin\\x64;C:\\pslibs\\extlib\\vstudio14\\Common7\\IDE;C:\\pslibs\\extlib\\vstudio14\\VC\\bin\\amd64;c:\\pslibs\\extlib\\dotnet\\v4.0.30319;C:\\cygwin\\bin;%PATH%")
  (setenv "VS100COMNTOOLS" "")
  (setenv "VS80COMNTOOLS" "")
  (setenv "VS90COMNTOOLS" "")
  (setenv "MSVCDIR" "C:\\pslibs\\extlib\\vstudio14\\VC")
  (setenv "CMPLR" "[VC2015 x64]")
  (setenv "PATH" "%PATH%;C:\\pslibs\\extlib\\tools\\jam\\2.5.4\\win.x86;C:\\pslibs\\extlib\\tools\\jam\\2.5.3\\win.x86;C:\\cygwin\\bin;C:\\pslibs\\extlib\\vstudio14\\VC\\bin\\amd64")
  (setq exec-path (append exec-path '("C:\\pslibs\\extlib\\vstudio14\\VC\\bin\\amd64"))))
